name: api_fetch

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.1.4
  http: ^0.13.4
  print_color: ^3.0.3
  shrink_sidemenu: ^2.0.0+1-null-safety

dev_dependencies:
  flutter_app_name: ^0.1.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_app_name:
  name: "NewsApp"

flutter:
  uses-material-design: true

  assets:
    - assets/loading.gif
